@startuml
'https://plantuml.com/class-diagram

class MatHang{
    - String ten
    - int soLuong
    - double donGia
    + MatHang(string ten, int sl, double gia)
    +  double ThanhTien()
    + String tótring()


}
interface IThanhToan{
    + double tinhTienGiam(Double tongTienHang)
 }
class ThanhToanCOD{
    + double tinhTienGiam(Double tongTienHang)
}
class ThanhToanAirPay{
    + double tinhTienGiam(Double tongTienHang)
}
interface IKhuyenMai{
    + double tinhTienKhuyenMai(Double tongTienHang)

}
class KhuyenMaiPhanTraMGiamToiDa{
    - double phanTramGiam
    - double maGiamToiDa
    + KhuyenMaiPhanTraMGiamToiDa(double phanTramGiam, double maGiamToiDa)
     + double tinhTienKhuyenMai(Double tongTienHang)
}
class GioHang{
    - List<MatHang> dsMH
    - IThanhToan hinhthucThanhToan
    - IKhuyenMai hinhthucKhuyenMai
    + void them(MatHang mh)
    + void setHinhThucThanhToan(IThanhToan tt)
    + void setHinhThucKhuyenMai(IKhuyenMai km)
    + double tinhTongTienHang()
    + void thanhToan()
}

IThanhToan <|.. ThanhToanCOD
IThanhToan <|.. ThanhToanAirPay
IKhuyenMai <|..KhuyenMaiPhanTraMGiamToiDa
GioHang --> MatHang: ds MatHang
GioHang o-> IThanhToan: hinhthucThanhToan
GioHang o-> IKhuyenMai: hinhthucKhuyenMai

@enduml
