@startuml
'https://plantuml.com/class-diagram

class VaccineCenter{
    -{static} VaccineCenter instance;
    - List<String> registerCitizens
    - VaccineCenter()
    + {static} VaccineCenter getInstance();
    + void add(String cccd)

}
class Citizen{
    - String cccd
    + Citizen(String cccd)
    + Register(String cd)

}
Citizen ..> VaccineCenter
VaccineCenter <-- VaccineCenter
@enduml