@startuml
'https://plantuml.com/class-diagram

class DataAccess{
    -{static} DataAccess instance
    -DataAccess()
    +{static} DataAccess getInstance()
    + void add(SanPham s)
    + void inDS()
}

class SanPhan{}

DataAccess *--> SanPhan:sps
@enduml