@startuml
'https://plantuml.com/class-diagram

class Referee{
    - {static} Referee instance;
    - List<String> cards

    -Referee()
    + {static} Referee getInstance()
    + void addCard(String detail)
    + showCard()
}

class Player{
    - playerName
    + void commitFoul()
}

Player ..> Referee: uses
Referee<-- Referee: instance

@enduml