@startuml
'https://plantuml.com/class-diagram

abstract XepLoaiHocSinh{
    String ten
    float nguong
    +{abstract} void hocSinh (diem)
    +{abstract} XepLoaiHocSinh xeploai(XepLoaiHocSinh xeploai)

}
class XuatSac
class XepLoai

XepLoaiHocSinh <|-- XuatSac
XepLoaiHocSinh <|-- XepLoai
XepLoai --> XepLoaiHocSinh:xeploai

@enduml