@startuml
'https://plantuml.com/class-diagram

abstract class IBinaryTreeComponent{
    int value
   +{abstract} void NRL()
   +{abstract} void addLeft(IBinaryTreeComponent c)
   +{abstract} void addRight(IBinaryTreeComponent c)
   +{abstract} void remove(IBinaryTreeComponent c)

}
class InternalNode
class LeafNode

IBinaryTreeComponent <|.. LeafNode
IBinaryTreeComponent <|.. InternalNode
InternalNode--> IBinaryTreeComponent:Left
InternalNode -->IBinaryTreeComponent:Right

@enduml